### ISSUE TITLE
Add documentation to: G4 Protocol Designer → Preview a pattern

### ISSUE THREAD

**Issue by floesche** [reiserlab/Modular-LED-Display#11]
[G4 Protocol Designer → Preview a pattern](https://reiserlab.github.io/Modular-LED-Display/Generation%204/Display_Tools/G4_Protocol_Designer/User-Instructions.html#previewing-an-experiment)

If I remember correctly there is now an option to preview a pattern on the arena (and change individual frames). It should be added

**Comment by taylorlm88** [comment]
added to docs

**Comment by floesche** [comment]
Just to keep track: There is a detailed section on preview at https://reiserlab.github.io/Modular-LED-Display/Generation%204/Display_Tools/docs/G4_Designer_Manual.html#previewing-an-experiment and several tutorials.
