### ISSUE TITLE
add documentation: G4 Protocol Designer → First fill out the metadata

### ISSUE THREAD

**Issue by floesche** [reiserlab/Modular-LED-Display#12]
[G4 Protocol Designer → First fill out the metadata](https://reiserlab.github.io/Modular-LED-Display/Generation%204/Display_Tools/G4_Protocol_Designer/User-Instructions.html#first-fill-out-the-metadata)

The documentation fo the protocol designer mentions a google sheet several times and relies on such a sheet to work. Provide some documentation what the google sheet looks like (maybe with example) and how to link your own to the designer and conductor.

**Comment by taylorlm88** [comment]
added to the docs and tutorial created on the subject

**Comment by floesche** [comment]
It's very well explained in https://reiserlab.github.io/Modular-LED-Display/Generation%204/Display_Tools/docs/G4_Designer_Manual.html#metadata-googlesheet-properties and there is an additional tutorial how to set up a google sheet at https://reiserlab.github.io/Modular-LED-Display/Generation%204/Display_Tools/docs/googlesheet_tutorial.html
