### ISSUE TITLE
add documentation to: G4 Protocol Designer → import files

### ISSUE THREAD

**Issue by floesche** [reiserlab/Modular-LED-Display#9]
[G4 Protocol Designer → Import files](https://reiserlab.github.io/Modular-LED-Display/Generation%204/Display_Tools/G4_Protocol_Designer/User-Instructions.html#the-designer-import-files)

Describe what are the imported files and what are the necessary files vs. optional files. For example, does an experiment always have to have a pattern file?

**Comment by taylorlm88** [comment]
clarified in getting started and docs. experiment design tutorial in progress

**Comment by floesche** [comment]
[Experiment design tutorial](https://reiserlab.github.io/Modular-LED-Display/Generation%204/Display_Tools/docs/experiment_tutorial.html) is now available. closing the issue.
